import pytest
import yaml

from click.testing import CliRunner


@pytest.fixture
def input_yaml_docker_compose():
    with open('tests/files/docker-compose.yml', 'r') as f:
        return yaml.safe_load(f)


@pytest.fixture
def output_yaml_docker_compose():
    with open('tests/files/docker-compose-secret.yml', 'r') as f:
        return yaml.safe_load(f)


def test_e2e_cli_secret_injector(input_yaml_docker_compose, output_yaml_docker_compose):
    """Ensure that the output generated by the CLI matches our desired."""
    assert input_yaml_docker_compose == output_yaml_docker_compose

